// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TLib/tool/tsystem_raid_master.proto

#ifndef PROTOBUF_TLib_2ftool_2ftsystem_5fraid_5fmaster_2eproto__INCLUDED
#define PROTOBUF_TLib_2ftool_2ftsystem_5fraid_5fmaster_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_TLib_2ftool_2ftsystem_5fraid_5fmaster_2eproto();
void protobuf_AssignDesc_TLib_2ftool_2ftsystem_5fraid_5fmaster_2eproto();
void protobuf_ShutdownFile_TLib_2ftool_2ftsystem_5fraid_5fmaster_2eproto();

class RaidMaster;

// ===================================================================

class RaidMaster : public ::google::protobuf::MessageLite {
 public:
  RaidMaster();
  virtual ~RaidMaster();

  RaidMaster(const RaidMaster& from);

  inline RaidMaster& operator=(const RaidMaster& from) {
    CopyFrom(from);
    return *this;
  }

  static const RaidMaster& default_instance();

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  // Returns the internal default instance pointer. This function can
  // return NULL thus should not be used by the user. This is intended
  // for Protobuf internal code. Please use default_instance() declared
  // above instead.
  static inline const RaidMaster* internal_default_instance() {
    return default_instance_;
  }
  #endif

  void Swap(RaidMaster* other);

  // implements Message ----------------------------------------------

  RaidMaster* New() const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const RaidMaster& from);
  void MergeFrom(const RaidMaster& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint32 pid = 1 [default = 0];
  inline bool has_pid() const;
  inline void clear_pid();
  static const int kPidFieldNumber = 1;
  inline ::google::protobuf::uint32 pid() const;
  inline void set_pid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:RaidMaster)
 private:
  inline void set_has_pid();
  inline void clear_has_pid();

  ::google::protobuf::uint32 pid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  #ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  friend void  protobuf_AddDesc_TLib_2ftool_2ftsystem_5fraid_5fmaster_2eproto_impl();
  #else
  friend void  protobuf_AddDesc_TLib_2ftool_2ftsystem_5fraid_5fmaster_2eproto();
  #endif
  friend void protobuf_AssignDesc_TLib_2ftool_2ftsystem_5fraid_5fmaster_2eproto();
  friend void protobuf_ShutdownFile_TLib_2ftool_2ftsystem_5fraid_5fmaster_2eproto();

  void InitAsDefaultInstance();
  static RaidMaster* default_instance_;
};
// ===================================================================


// ===================================================================

// RaidMaster

// optional uint32 pid = 1 [default = 0];
inline bool RaidMaster::has_pid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RaidMaster::set_has_pid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RaidMaster::clear_has_pid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RaidMaster::clear_pid() {
  pid_ = 0u;
  clear_has_pid();
}
inline ::google::protobuf::uint32 RaidMaster::pid() const {
  return pid_;
}
inline void RaidMaster::set_pid(::google::protobuf::uint32 value) {
  set_has_pid();
  pid_ = value;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_TLib_2ftool_2ftsystem_5fraid_5fmaster_2eproto__INCLUDED
